collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3528464
  brandStrength: 0.472073
  lightness: 0.2060184
  brandColors:
    - '#020202'
    - '#302F2D'
    - '#555452'
    - '#FFFFFF'
    - '#C7C3C0'
  rhythmicContrast: 0.359291
typography_spectrum: 0.4727275
layout_spectrum: 0.04156202
name: Phasetwo
